name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.py-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install Python ${{ matrix.py-version }}
        run: uv python install ${{ matrix.py-version }}

      - name: Install
        run: |
          uv venv
          uv pip install -r tests/requirements.txt --editable .

      - name: Run tests for ${{ matrix.python-version }} on ${{ matrix.os }}
        run: uv run pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
